# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'appProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for appProject

  target 'appProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'appProjectUITests' do
    # Pods for testing
  end

end
